module.exports = {
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRETKEY: process.env.GOOGLE_CLIENT_SECRETKEY,
    MONGOOSE_URI: process.env.MONGOOSE_URI,
    COOKIE_KEY: process.env.COOKIE_KEY,
    STRIPE_PUBLISH_KAY: process.env.STRIPE_PUBLISH_KAY,
    STRIPE_SEC_KEY: process.env.STRIPE_SEC_KEY,
    SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
    REDIRECT_DOMAIN: process.env.REDIRECT_DOMAIN
}